ktor:
  deployment:
    port: 8080
  application:
    modules:
      - websote.woodendoor.SerializationKt.configureSerialization
      - websote.woodendoor.StatusPagesKt.configureStatusPages
      - websote.woodendoor.RoutingKt.configureRouting
